<a href="https://colab.research.google.com/github/NickPetrilli/AI/blob/main/lab05_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Artificial Intelligence

Lab 05

By Nick Petrilli

8 October 2023

In [ ]:
# Part II - Upload the Circuit1 xlsx spreadsheet to Colab.
from google.colab import files

# Upload a file
uploaded = files.upload()

filename = "Petrilli-lab05.xlsx"

# Read the uploaded file
for filename, content in uploaded.items():
    print("Uploaded:", filename)
    print("Content:", content)

Saving Petrilli-lab05.xlsx to Petrilli-lab05.xlsx
Uploaded: Petrilli-lab05.xlsx
Content: b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x9e,lok\x01\x00\x00\x10\x05\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\

In [ ]:
# Part III - Read in the XOR data
import pandas as pd

df = pd.read_excel(filename)

print(df)

   X1  X2  X3  OR(X1, X2)  NAND(X2, X3)  Y1
0   0   0   0           0             1   1
1   0   0   1           0             1   1
2   0   1   0           1             1   0
3   0   1   1           1             0   1
4   1   0   0           1             1   0
5   1   0   1           1             1   0
6   1   1   0           1             1   0
7   1   1   1           1             0   1


In [ ]:
import numpy as np

xInputs = []
yLabels = []

for index in range(len(df)):
  row = df.iloc[index]
  # Access row data using row['column_name']
  xInputs.append([row['X1'], row['X2'], row['X3']])
  yLabels.append(row['Y1'])

# print(xInputs)
# print(yLabels)

X = np.array(xInputs)
y = np.array(yLabels)

print(X)
print(y)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[1 1 0 1 0 0 0 1]


In [ ]:
# Import the modules from Keras which we can get from Keras or Keras of tensorflow.
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import Constant

In [ ]:
# Part IV - Build the model.

# Create the model with three inputs and one output
model = Sequential()

# Default bias is 0.0 -- we set it to 1.0 as an experiment.
model.add(Dense(3, input_dim=3, activation='relu', bias_initializer=Constant(1.0)))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# Compile the model parameters
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# This class definition may give "keras not defined warning..." To fix, import Keras
# from tensorflow as shown above.
class DiagnosticCallback(keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % 100 == 0:
            print(f"Epoch {epoch + 1}: loss = {logs['loss']:.4f}, accuracy = {logs['accuracy']:.4f}")

In [ ]:
# Part V - Train the model

# Set verbose=0 to suppress ALL diagnostics or use the diagnostic callback defined
# above -- apparently there's no other way to ask for SOME periodic diagnostics.
NUM_EPOCHS = 2000
model.fit(X, y, epochs=NUM_EPOCHS, verbose=0,callbacks=[DiagnosticCallback()])

Epoch 100: loss = 0.0015, accuracy = 1.0000
Epoch 200: loss = 0.0014, accuracy = 1.0000
Epoch 300: loss = 0.0013, accuracy = 1.0000
Epoch 400: loss = 0.0013, accuracy = 1.0000
Epoch 500: loss = 0.0012, accuracy = 1.0000
Epoch 600: loss = 0.0012, accuracy = 1.0000
Epoch 700: loss = 0.0011, accuracy = 1.0000
Epoch 800: loss = 0.0011, accuracy = 1.0000
Epoch 900: loss = 0.0010, accuracy = 1.0000
Epoch 1000: loss = 0.0010, accuracy = 1.0000
Epoch 1100: loss = 0.0009, accuracy = 1.0000
Epoch 1200: loss = 0.0009, accuracy = 1.0000
Epoch 1300: loss = 0.0009, accuracy = 1.0000
Epoch 1400: loss = 0.0008, accuracy = 1.0000
Epoch 1500: loss = 0.0008, accuracy = 1.0000
Epoch 1600: loss = 0.0008, accuracy = 1.0000
Epoch 1700: loss = 0.0007, accuracy = 1.0000
Epoch 1800: loss = 0.0007, accuracy = 1.0000
Epoch 1900: loss = 0.0007, accuracy = 1.0000
Epoch 2000: loss = 0.0006, accuracy = 1.0000


In [ ]:
# Make predictions against all the actual inputs.
# Sometimes you might a warning, "WARNING:tensorflow:5 out of the last 5 calls...""
predictions = model.predict(X)

1/1 [==============================] - 0s 52ms/step


In [ ]:
# Print the predictions.
# Look ever these outputs: notice that they are often far from the ideal or
# labelled outputs.
for i in range(len(X)):
    print(f"Input: {X[i]}, Predicted Output: {np.round(predictions[i].item(), 4)} => {np.round(predictions[i].item())}")
    # Some of the numbers are very small negative exponents, which round to 0

Input: [0 0 0], Predicted Output: 0.9988 => 1.0
Input: [0 0 1], Predicted Output: 0.9988 => 1.0
Input: [0 1 0], Predicted Output: 0.0002 => 0.0
Input: [0 1 1], Predicted Output: 0.9988 => 1.0
Input: [1 0 0], Predicted Output: 0.0 => 0.0
Input: [1 0 1], Predicted Output: 0.0001 => 0.0
Input: [1 1 0], Predicted Output: 0.0 => 0.0
Input: [1 1 1], Predicted Output: 0.9988 => 1.0
